{
 "title": "EVCC: Mese",
 "time": { "from": "now-1M/M", "to": "now-1M/M" },
 "templating": {
  "list": [
   { "name": "timezone", "label": "Time zone", "query": "${VAR_TIMEZONE}" },
   { "name": "peakPowerLimit", "label": "Maximum power filter / W", "query": "${VAR_PEAKPOWERLIMIT}" },
   { "name": "installedWattPeak", "label": "Installed capacity in Wp", "query": "${VAR_INSTALLEDWATTPEAK}" },
   { "name": "loadpointBlocklist", "label": "Loadpoint blocklist", "query": "${VAR_LOADPOINTBLOCKLIST}" }
  ]
 },
 "panels": [
  { "title": "PV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Energia",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "range_sum(avg(pvEnergyDaily[1d]))",
     "legendFormat": "pvEnergy",
     "trace": 1
    },
    {
     "expr": "range_sum(avg(gridEnergyImportDaily[1d]))",
     "legendFormat": "gridEnergyImport",
     "trace": 1
    },
    {
     "expr": "range_sum(avg(gridEnergyExportDaily[1d]))",
     "legendFormat": "gridEnergyExport",
     "trace": 1
    },
    {
     "expr": "range_sum(avg(homeEnergyDaily[1d]))",
     "legendFormat": "homeEnergy",
     "trace": 1
    },
    {
     "expr": "range_sum(avg(batteryEnergyDischargedDaily[1d]))",
     "legendFormat": "batteryEnergyDischarged",
     "trace": 1
    },
    {
     "expr": "range_sum(avg(batteryEnergyChargedDaily[1d]))",
     "legendFormat": "batteryEnergyCharged",
     "trace": 1
    },
    {
     "expr": "range_sum(avg by (loadpoint)(loadpointEnergyDaily[1d]))",
     "legendFormat": "{{loadpoint}}",
     "trace": 1
    },
    { "expr": "0", "legendFormat": "workaround" }
   ]
  },
  {
   "title": "Energie giornaliere",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "avg(pvEnergyDaily[1d])", "legendFormat": "pvEnergy", "trace": 1 },
    { "expr": "avg(gridEnergyImportDaily[1d])", "legendFormat": "gridEnergyImport", "trace": 1 },
    { "expr": "avg(homeEnergyDaily[1d])", "legendFormat": "homeEnergy", "trace": 1 },
    {
     "expr": "avg by (loadpoint)(loadpointEnergyDaily[1d])",
     "legendFormat": "{{loadpoint}}",
     "trace": 1
    },
    { "expr": "avg(gridEnergyExportDaily[1d])", "legendFormat": "gridEnergyExport", "trace": 1 }
   ]
  },
  {
   "title": "Specific yield",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kWh/kWp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$pvEnergy/$installedWattPeak", "type": "math" }
   ]
  },
  {
   "title": "Key figures",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "1-$zugekaufteEnergie/($energieLoadpoints + $energieHaus)",
     "type": "math"
    },
    {
     "expression": "($energiePV - $eingespeisteEnergie)/$energiePV",
     "type": "math"
    }
   ]
  },
  { "gridPos": { "h": 10, "w": 5, "x": 0, "y": 17 } },
  { "gridPos": { "h": 6, "w": 5, "x": 0, "y": 27 } },
  { "title": "Casa", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Home: energy distribution",
   "type": "piechart",
   "description": "The formula for 'Other' must be adjusted depending on the availability of AUX and EXT meters. See https://github.com/ha-puzzles/evcc-grafana-dashboards/tree/main/dashboards for more information.",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expression": "$homeTotal - $extEnergiesSum", "type": "math" },
    {
     "alias": "$tag_title",
     "query": "SELECT value FROM extDailyEnergy WHERE $timeFilter AND \"title\"::tag !~ $loadpointBlocklist GROUP BY (\"title\"::tag) tz('$timezone')"
    },
    {
     "alias": "$tag_title",
     "query": "SELECT value FROM auxDailyEnergy WHERE $timeFilter AND \"title\"::tag !~ $loadpointBlocklist GROUP BY (\"title\"::tag) tz('$timezone')"
    }
   ]
  },
  {
   "title": "Home: energy consumption",
   "type": "barchart",
   "description": "The formula for 'Other' must be adjusted depending on the availability of AUX and EXT meters. See https://github.com/ha-puzzles/evcc-grafana-dashboards/tree/main/dashboards for more information.",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expression": "$homeTotal - $extEnergiesSum", "type": "math" },
    {
     "alias": "$tag_title",
     "query": "SELECT value FROM extDailyEnergy WHERE $timeFilter AND \"title\"::tag !~ $loadpointBlocklist GROUP BY (\"title\"::tag) tz('$timezone')"
    },
    {
     "alias": "$tag_title",
     "query": "SELECT value FROM auxDailyEnergy WHERE $timeFilter AND \"title\"::tag !~ $loadpointBlocklist GROUP BY (\"title\"::tag) tz('$timezone')"
    }
   ]
  },
  {
   "title": "Totale: distribuzione dell'energia",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Home",
     "query": "SELECT value FROM homeDailyEnergy WHERE $timeFilter  tz('$timezone')"
    },
    {
     "alias": "$tag_loadpoint",
     "query": "SELECT value FROM loadpointDailyEnergy WHERE $timeFilter AND \"loadpoint\"::tag !~ $loadpointBlocklist GROUP BY (\"loadpoint\"::tag) tz('$timezone')"
    },
    {
     "expression": "$chargeEnergy - $dischargeEnergy",
     "type": "math"
    }
   ]
  },
  {
   "title": "Totale: distribuzione dell'energia",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expression": "$chargeEnergy-$dischargeEnergy", "type": "math" },
    {
     "alias": "Home",
     "query": "SELECT value FROM homeDailyEnergy WHERE $timeFilter  tz('$timezone')"
    },
    {
     "alias": "$tag_loadpoint",
     "query": "SELECT value FROM loadpointDailyEnergy WHERE $timeFilter AND \"loadpoint\"::tag !~ $loadpointBlocklist GROUP BY (\"loadpoint\"::tag) tz('$timezone')"
    }
   ]
  },
  { "gridPos": { "h": 18, "w": 5, "x": 0, "y": 56 } },
  { "gridPos": { "h": 11, "w": 19, "x": 5, "y": 56 } },
  {
   "title": "Electricity costs",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "alias": "Purchase",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvPower",
     "query": "SELECT value FROM energyPurchasedDailyPrice WHERE $timeFilter  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Sale",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvPower",
     "query": "SELECT value FROM energySoldDailyPrice WHERE $timeFilter  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Batteria", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  { "gridPos": { "h": 7, "w": 5, "x": 0, "y": 75 } },
  {
   "title": "Home battery levels",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 75 },
   "targets": [
    {
     "alias": "Battery max",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT \"value\" FROM \"batteryMaxSoc\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Battery min",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT \"value\" FROM \"batteryMinSoc\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}