{
 "title": "EVCC: Vandaag - Details",
 "tags": [ "EVCC" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "peakPowerLimit", "label": "Maximale vermogenslimiet / W", "query": "${VAR_PEAKPOWERLIMIT}" },
   { "name": "loadpointBlocklist", "label": "Uitgesloten laadpunten", "query": "${VAR_LOADPOINTBLOCKLIST}" },
   { "name": "extBlocklist", "label": "Uitgesloten EXT-apparaten", "query": "${VAR_EXTBLOCKLIST}" },
   { "name": "auxBlocklist", "label": "Uitgesloten AUX-apparaten", "query": "${VAR_AUXBLOCKLIST}" },
   { "name": "loadpoint", "label": "Laadpunt", "query": { "query": "label_values(loadpoint)" } },
   { "name": "energySampleInterval", "label": "Bemonsteringsinterval", "query": "${VAR_ENERGYSAMPLEINTERVAL}" },
   { "name": "tariffPriceInterval", "label": "Prijsinterval", "query": "${VAR_TARIFFPRICEINTERVAL}" }
  ]
 },
 "panels": [
  { "title": "PV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Zonne-energie",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "sort_by_label(\n    integrate(\n        ((pvPower_value{title!=\"\", title !~ \"$extBlocklist\"} < $peakPowerLimit) default 0)[1d:$energySampleInterval]\n    ) / 3600000\n, \"title\")",
     "legendFormat": "{{title}}"
    },
    { "expr": "0", "legendFormat": "workaround" },
    {
     "expr": "sum(\n    integrate(\n        ((pvPower_value{id=\"\"} < $peakPowerLimit) default 0)[1d:$energySampleInterval]\n    ) / 3600000\n)",
     "legendFormat": "pvEnergy"
    }
   ]
  },
  {
   "title": "Zonnevermogen",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sort_by_label(avg by (title)(pvPower_value{title!=\"\"}), \"title\")",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Laadtoestand van de batterij",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sort_by_label(avg by (title) (range_last(batterySoc_value{id!=\"\", title!=\"\"})), \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "batterySoc_value{id=\"\"}",
     "legendFormat": "totalSoc"
    }
   ]
  },
  {
   "title": "Batterijvermogen",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg by (title)(batteryPower_value{id!=\"\"})",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "Voorspelling",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "expr": "sum(\n    integrate(\n        ((tariffSolar_value) default 0)[1d:$energySampleInterval]\n    ) / 3600000\n)",
     "legendFormat": "pvForecastEnergy"
    },
    {
     "expr": "sum(\n    integrate(\n        ((pvPower_value{id=\"\"} < $peakPowerLimit) default 0)[1d:$energySampleInterval]\n    ) / 3600000\n)",
     "legendFormat": "pvEnergy"
    },
    { "expr": "min(chargePower_value)", "legendFormat": "workaround" }
   ]
  },
  {
   "title": "Voorspelling",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "avg(tariffSolar_value)", "legendFormat": "forecast" },
    {
     "expr": "pvPower_value{id=\"\"}",
     "legendFormat": "pvPower"
    }
   ]
  },
  { "title": "Verbruik", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Huis: actuele vermogens",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}), \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}), \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "avg(homePower_value) - avg(sum(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}) default 0)  - avg(sum(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}) default 0)",
     "legendFormat": "otherPowers"
    }
   ]
  },
  {
   "title": "Huis: vermogens",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sort_by_label(avg by (title)(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}), \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(avg by (title)(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}), \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "avg(homePower_value) - avg(sum(extPower_value{title!=\"\", title !~ \"$extBlocklist\"}) default 0) - avg(sum(auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"}) default 0)",
     "legendFormat": "otherPowers"
    }
   ]
  },
  {
   "title": "Huis: energieverdeling",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(\n    range_last(\n        integrate(\n            ((extPower_value{title!=\"\", title !~ \"$extBlocklist\"} < $peakPowerLimit) default 0)[1d:$energySampleInterval]\n        ) / 3600\n    )\n, \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "range_last(\n    sum(\n        integrate(\n            ((homePower_value < $peakPowerLimit) default 0)[1d:$energySampleInterval]\n        ) / 3600\n    )\n)\n-\nrange_last(\n    sum(\n        integrate(\n            ((extPower_value{title!=\"\", title !~ \"$extBlocklist\"} < $peakPowerLimit) default 0)[1d:$energySampleInterval]\n        ) / 3600\n    )\n)\n-\nrange_last(\n    sum(\n        integrate(\n            ((auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"} < $peakPowerLimit) default 0)[1d:$energySampleInterval]\n        ) / 3600\n    )\n)",
     "legendFormat": "otherEnergies"
    }
   ]
  },
  {
   "title": "Huis: uurlijkse energieverdeling",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sort_by_label(\n    integrate(\n        ((extPower_value{title!=\"\", title !~ \"$extBlocklist\"} < $peakPowerLimit) default 0)[1h:$energySampleInterval] offset -1h\n    ) / 3600\n, \"title\")",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sum(\n    integrate(\n        ((homePower_value < $peakPowerLimit) default 0)[1h:$energySampleInterval] offset -1h\n    ) / 3600\n)\n-\nsum(\n    integrate(\n        ((extPower_value{title!=\"\", title !~ \"$extBlocklist\"} < $peakPowerLimit) default 0)[1h:$energySampleInterval] offset -1h\n    ) / 3600\n)\n-\nsum(\n    integrate(\n        ((auxPower_value{title!=\"\", title !~ \"$auxBlocklist\"} < $peakPowerLimit) default 0)[1h:$energySampleInterval] offset -1h\n    ) / 3600\n)",
     "legendFormat": "otherEnergies"
    }
   ]
  },
  {
   "title": "Totaal: energieverdeling",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "range_last(\n    integrate(\n        ((homePower_value < $peakPowerLimit) default 0)[1d:$energySampleInterval]\n    ) / 3600\n)",
     "legendFormat": "totalHomeEnergy"
    },
    {
     "expr": "sort_by_label(\n    range_last(\n        sum by (loadpoint)(\n            integrate(\n                ((chargePower_value{loadpoint!=\"\", loadpoint !~ \"$loadpointBlocklist\"} < $peakPowerLimit) default 0)[1d:$energySampleInterval]\n            ) / 3600\n        )\n    )\n, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    }
   ]
  },
  {
   "title": "Totaal: uurlijkse energieverdeling",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "integrate(\n    ((homePower_value < $peakPowerLimit) default 0)[1h:$energySampleInterval] offset -1h\n) / 3600",
     "legendFormat": "totalHomeEnergy"
    },
    {
     "expr": "sort_by_label(\n    sum by (loadpoint)(\n        integrate(\n            ((chargePower_value{loadpoint!=\"\", loadpoint !~ \"$loadpointBlocklist\"} < $peakPowerLimit) default 0)[1h:$energySampleInterval] offset -1h\n        ) / 3600\n    )\n, \"loadpoint\")",
     "legendFormat": "{{loadpoint}}"
    }
   ]
  },
  { "title": "Tarieven", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Tariefprijs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(avg(tariffGrid_value)[1d])",
     "legendFormat": "maxPrice"
    },
    {
     "expr": "avg_over_time(avg(tariffGrid_value)[1d])",
     "legendFormat": "avgPrice"
    },
    {
     "expr": "min_over_time(avg(tariffGrid_value)[1d])",
     "legendFormat": "minPrice"
    }
   ]
  },
  {
   "title": "Tariefprijs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 56 },
   "targets": [
    {
     "expr": "avg(tariffGrid_value offset -$tariffPriceInterval)",
     "legendFormat": "price"
    },
    {
     "expr": "clamp_min(avg(gridPower_value offset -$tariffPriceInterval), 0)",
     "legendFormat": "gridPowerImport"
    }
   ]
  },
  {
   "title": "Energiekosten",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "range_sum(\n    avg(tariffGrid_value offset -$tariffPriceInterval)\n    *\n    integrate(\n        ((gridPower_value > 0 < $peakPowerLimit) default 0)[$tariffPriceInterval:$energySampleInterval] offset -$tariffPriceInterval\n    ) / 3600000\n)",
     "legendFormat": "bought"
    },
    {
     "expr": "range_sum(\n    avg(tariffFeedIn_value offset -$tariffPriceInterval)\n    *\n    integrate(\n        ((gridPower_value < 0 < $peakPowerLimit) default 0)[$tariffPriceInterval:$energySampleInterval] offset -$tariffPriceInterval\n    ) / 3600000\n)",
     "legendFormat": "sold"
    },
    { "expression": "$bought + $sold", "type": "math" }
   ]
  },
  {
   "title": "Energiekosten",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "avg(tariffGrid_value offset -$tariffPriceInterval)\n*\nintegrate(\n    ((gridPower_value > 0 < $peakPowerLimit) default 0)[$tariffPriceInterval:$energySampleInterval] offset -$tariffPriceInterval\n) / 3600000",
     "legendFormat": "bought"
    },
    {
     "expr": "avg(tariffFeedIn_value offset -$tariffPriceInterval)\n*\nintegrate(\n    ((gridPower_value < 0 < $peakPowerLimit) default 0)[$tariffPriceInterval:$energySampleInterval] offset -$tariffPriceInterval\n) / 3600000",
     "legendFormat": "sold"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "g/kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(avg(tariffCo2_value)[1d])",
     "legendFormat": "Max"
    },
    {
     "expr": "avg_over_time(avg(tariffCo2_value)[1d])",
     "legendFormat": "Gemiddelde"
    },
    {
     "expr": "min_over_time(avg(tariffCo2_value)[1d])",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 74 },
   "targets": [
    {
     "expr": "tariffCo2_value offset -$tariffPriceInterval",
     "legendFormat": "CO2"
    },
    { "expr": "clamp_min(gridPower_value, 0)", "legendFormat": "Netafname" }
   ]
  },
  { "title": "Net", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Stroom per fase",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "range_last(avg(gridCurrents_l1))",
     "legendFormat": "currentL1"
    },
    {
     "expr": "range_last(avg(gridCurrents_l2))",
     "legendFormat": "currentL2"
    },
    {
     "expr": "range_last(avg(gridCurrents_l3))",
     "legendFormat": "currentL3"
    }
   ]
  },
  {
   "title": "Stroom per fase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "avg(gridCurrents_l1)", "legendFormat": "currentL1" },
    { "expr": "avg(gridCurrents_l2)", "legendFormat": "currentL2" },
    { "expr": "avg(gridCurrents_l3)", "legendFormat": "currentL3" }
   ]
  },
  {
   "title": "Vermogen per fase",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "range_last(avg(gridPowers_l1))", "legendFormat": "powerL1" },
    { "expr": "range_last(avg(gridPowers_l2))", "legendFormat": "powerL2" },
    { "expr": "range_last(avg(gridPowers_l3))", "legendFormat": "powerL3" }
   ]
  },
  {
   "title": "Vermogen per fase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "avg(gridPowers_l1)", "legendFormat": "powerL1" },
    { "expr": "avg(gridPowers_l2)", "legendFormat": "powerL2" },
    { "expr": "avg(gridPowers_l3)", "legendFormat": "powerL3" }
   ]
  },
  { "title": "Laadpunt $loadpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 }, "repeat": "loadpoint" },
  {
   "title": "Laadstroom per fase: $loadpoint",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "range_last(avg(chargeCurrents_l1{loadpoint=\"$loadpoint\"}))",
     "legendFormat": "currentL1"
    },
    {
     "expr": "range_last(avg(chargeCurrents_l2{loadpoint=\"$loadpoint\"}))",
     "legendFormat": "currentL2"
    },
    {
     "expr": "range_last(avg(chargeCurrents_l2{loadpoint=\"$loadpoint\"}))",
     "legendFormat": "currentL3"
    }
   ]
  },
  {
   "title": "Laadstroom per fase: $loadpoint",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "avg(chargeCurrents_l1 {loadpoint=\"$loadpoint\"})",
     "legendFormat": "currentL1"
    },
    {
     "expr": "avg(chargeCurrents_l2 {loadpoint=\"$loadpoint\"})",
     "legendFormat": "currentL2"
    },
    {
     "expr": "avg(chargeCurrents_l3 {loadpoint=\"$loadpoint\"})",
     "legendFormat": "currentL3"
    }
   ]
  },
  {
   "title": "Aantal actieve fasen: $loadpoint",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 112 },
   "targets": [
    {
     "expr": "avg(phasesActive_value{loadpoint=\"$loadpoint\"}) < 2",
     "legendFormat": "1P"
    },
    {
     "expr": "avg(phasesActive_value{loadpoint=\"$loadpoint\"}) > 2",
     "legendFormat": "3P"
    }
   ]
  },
  {
   "title": "Laadvermogen: $loadpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(chargePower_value {loadpoint=\"$loadpoint\"})",
     "legendFormat": "chargePower"
    }
   ]
  }
 ]
}