{
 "title": "EVCC: Month",
 "time": { "from": "now/M", "to": "now/M" },
 "templating": {
  "list": [
   { "name": "installedWattPeak", "label": "Installed capacity in Wp", "query": "${VAR_INSTALLEDWATTPEAK}" },
   { "name": "loadpointBlocklist", "label": "Excluded loadpoints", "query": "${VAR_LOADPOINTBLOCKLIST}" },
   { "name": "extBlocklist", "label": "Excluded EXT devices", "query": "${VAR_EXTBLOCKLIST}" },
   { "name": "auxBlocklist", "label": "Excluded  AUX devices", "query": "${VAR_AUXBLOCKLIST}" }
  ]
 },
 "panels": [
  { "title": "PV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Energy",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "range_sum(avg(pvEnergyDaily[1d]))",
     "legendFormat": "pvEnergy",
     "trace": 1
    },
    {
     "expr": "range_sum(avg(gridEnergyImportDaily[1d]))",
     "legendFormat": "gridEnergyImport",
     "trace": 1
    },
    {
     "expr": "range_sum(avg(gridEnergyExportDaily[1d])) * (-1)",
     "legendFormat": "gridEnergyExport",
     "trace": 1
    },
    {
     "expr": "range_sum(avg(homeEnergyDaily[1d])) * (-1)",
     "legendFormat": "homeEnergy",
     "trace": 1
    },
    {
     "expr": "range_sum(avg(batteryEnergyDischargedDaily[1d])) * (-1)",
     "legendFormat": "batteryEnergyDischarged",
     "trace": 1
    },
    {
     "expr": "range_sum(avg(batteryEnergyChargedDaily[1d]))",
     "legendFormat": "batteryEnergyCharged",
     "trace": 1
    },
    {
     "expr": "range_sum(avg by (loadpoint)(loadpointEnergyDaily[1d])) * (-1)",
     "legendFormat": "{{loadpoint}}",
     "trace": 1
    },
    { "expr": "0", "legendFormat": "workaround" }
   ]
  },
  {
   "title": "Daily energies",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "avg(pvEnergyDaily[1d])", "legendFormat": "pvEnergy", "trace": 1 },
    { "expr": "avg(gridEnergyImportDaily[1d])", "legendFormat": "gridEnergyImport", "trace": 1 },
    {
     "expr": "avg(homeEnergyDaily[1d]) * (-1)",
     "legendFormat": "homeEnergy",
     "trace": 1
    },
    {
     "expr": "avg by (loadpoint)(loadpointEnergyDaily{loadpoint !~ \"$loadpointBlocklist\"}[1d]) * (-1)",
     "legendFormat": "{{loadpoint}}",
     "trace": 1
    },
    {
     "expr": "avg(gridEnergyExportDaily[1d]) * (-1)",
     "legendFormat": "gridEnergyExport",
     "trace": 1
    }
   ]
  },
  {
   "title": "KPIs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - ( range_sum(avg(gridEnergyImportDaily[1d])) / (range_sum(avg(homeEnergyDaily[1d])) + range_sum(sum(loadpointEnergyDaily[1d]))) )",
     "legendFormat": "autonomy"
    },
    {
     "expr": "(range_sum(avg(pvEnergyDaily[1d])) - range_sum(avg(gridEnergyExportDaily[1d]))) / range_sum(avg(pvEnergyDaily[1d]))",
     "legendFormat": "selfSufficiency"
    }
   ]
  },
  {
   "title": "KPIs",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ( avg(gridEnergyImportDaily[1d]) / (avg(homeEnergyDaily[1d]) + sum(loadpointEnergyDaily[1d])) )",
     "legendFormat": "autonomy"
    },
    {
     "expr": "(avg(pvEnergyDaily[1d]) - avg(gridEnergyExportDaily[1d])) / avg(pvEnergyDaily[1d])",
     "legendFormat": "selfSufficiency"
    }
   ]
  },
  {
   "title": "Specific yield",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kWh/kWp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "range_sum(avg(pvEnergyDaily[1d])) / $installedWattPeak",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Haus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Home: energy distribution",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sort_by_label(avg by (title)(extEnergyDaily{title !~ \"$extBlocklist\"} [1d]), \"title\") !=0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sort_by_label(avg by (title)(auxEnergyDaily{title !~ \"$auxBlocklist\"} [1d]), \"title\") !=0",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(homeEnergyDaily[1d]) - (sum(avg by (title)(auxEnergyDaily{title !~ \"$auxBlocklist\"} [1d]) !=0))",
     "legendFormat": "otherEnergy"
    },
    {
     "expr": "avg(homeEnergyDaily[1d]) - (sum(avg by (title)(extEnergyDaily{title !~ \"$extBlocklist\"} [1d])) !=0 )",
     "legendFormat": "otherEnergy"
    },
    {
     "expr": "avg(homeEnergyDaily[1d]) - (sum(avg by (title)(extEnergyDaily{title !~ \"$extBlocklist\"} [1d]) !=0) - (sum(avg by (title)(auxEnergyDaily{title !~ \"$auxBlocklist\"} <0 [1d]) !=0)))",
     "legendFormat": "otherEnergy"
    }
   ]
  },
  {
   "title": "Home: daily energy distribution",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sort_by_label(avg by (title)(extEnergyDaily{title !~ \"$extBlocklist\"} [1d]), \"title\") !=0",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "sort_by_label(avg by (title)(auxEnergyDaily{title !~ \"$auxBlocklist\"} [1d]), \"title\") !=0",
     "legendFormat": "{{title}}"
    },
    {
     "expr": "avg(homeEnergyDaily[1d]) - (sum(avg by (title)(auxEnergyDaily{title !~ \"$auxBlocklist\"} [1d]) !=0))",
     "legendFormat": "otherEnergy"
    },
    {
     "expr": "avg(homeEnergyDaily[1d]) - (sum(avg by (title)(extEnergyDaily{title !~ \"$extBlocklist\"} [1d])) !=0 )",
     "legendFormat": "otherEnergy"
    },
    {
     "expr": "avg(homeEnergyDaily[1d]) - (sum(avg by (title)(extEnergyDaily{title !~ \"$extBlocklist\"} [1d]) !=0) - (sum(avg by (title)(auxEnergyDaily{title !~ \"$auxBlocklist\"} <0 [1d]) !=0)))",
     "legendFormat": "otherEnergy"
    }
   ]
  },
  {
   "title": "Total energy distribution",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "avg(batteryEnergyChargedDaily[1d]) - avg(batteryEnergyDischargedDaily[1d])",
     "legendFormat": "batteryEnergy"
    },
    { "expr": "avg(homeEnergyDaily[1d])", "legendFormat": "homeEnergy" },
    {
     "expr": "avg by (loadpoint)(loadpointEnergyDaily{loadpoint !~ \"$loadpointBlocklist\"}[1d])",
     "legendFormat": "{{loadpoint}}"
    }
   ]
  },
  {
   "title": "Total daily energy distribution",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "avg(batteryEnergyChargedDaily[1d]) - avg(batteryEnergyDischargedDaily[1d])",
     "legendFormat": "batteryEnergy"
    },
    { "expr": "avg(homeEnergyDaily[1d])", "legendFormat": "homeEnergy" },
    {
     "expr": "avg by (loadpoint)(loadpointEnergyDaily{loadpoint !~ \"$loadpointBlocklist\"}[1d])",
     "legendFormat": "{{loadpoint}}"
    }
   ]
  },
  { "gridPos": { "h": 18, "w": 5, "x": 0, "y": 46 } },
  {
   "title": "Strompreis",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ct" } },
   "targets": [
    {
     "expr": "avg(energyPriceMaxDaily[1d]) * 100",
     "legendFormat": "energyPriceMax"
    },
    {
     "expr": "avg(energyPriceAvgDaily[1d]) * 100",
     "legendFormat": "energyPriceAvg"
    },
    {
     "expression": "($purchased * 100 )/ $gridEnergyImport",
     "type": "math"
    },
    {
     "expr": "avg(energyPriceMinDaily[1d]) * 100",
     "legendFormat": "energyPriceMin"
    }
   ]
  },
  {
   "title": "Stromkosten",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "avg(energyPriceBoughtDaily[1d])",
     "legendFormat": "energyPriceBought"
    },
    {
     "expr": "avg(energyPriceSoldDaily[1d]) * (-1)",
     "legendFormat": "energyPriceSold"
    }
   ]
  },
  { "title": "Speicher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  { "gridPos": { "h": 7, "w": 5, "x": 0, "y": 65 } },
  {
   "title": "Hausspeicher Stände",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 65 },
   "targets": [
    {
     "alias": "Speicher max",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT \"value\" FROM \"batteryMaxSoc\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Speicher min",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT \"value\" FROM \"batteryMinSoc\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}