{
 "title": "PV All-time",
 "tags": [ "PV" ],
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   { "name": "pvAnschaffungspreis", "label": "PV Gesamtinvestitionskosten", "query": "24884" },
   { "name": "speicherPreis", "label": "Investitionskosten Speicher", "query": "5500" },
   { "name": "stromPreis", "label": "Strompreis", "query": "0.28, 0.32" },
   { "name": "einspeiseVerguetung", "label": "Einspeisevergütung", "query": "0.082" },
   { "name": "jaehrlicheKosten", "label": "Jährliche Kosten", "query": "100" },
   { "name": "speicherkapazitaet", "label": "Speicherkapazität/Wh", "query": "9500" },
   { "name": "eVerbrauch", "label": "Elektro Verbrauch kWh/100km", "query": "18" },
   { "name": "vVerbrauch", "label": "Verbrenner Verbrauch l/100km", "query": "6" },
   { "name": "spritKosten", "label": "Spritpreis/Liter", "query": "1.70" }
  ]
 },
 "panels": [
  { "title": "Statistiken", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "gridPos": { "h": 11, "w": 4, "x": 0, "y": 1 } },
  {
   "title": "Monatlicher Ertrag/Jahr",
   "type": "barchart",
   "description": "Die Legende sollte das Jahr anzeigen, aber ein Bug in Grafana verhindert das: https://github.com/grafana/grafana/issues/87332",
   "gridPos": { "h": 11, "w": 16, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT year, month, value FROM \"pvMonthlyEnergy\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "gridPos": { "h": 11, "w": 4, "x": 20, "y": 1 } },
  { "title": "Finanzen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Monatliche Kosten",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expression": "$verbrauchGesamt/1000 * $stromPreis",
     "type": "math"
    },
    {
     "expression": "$zugekauft30Tage/1000 * $stromPreis",
     "type": "math"
    },
    {
     "expression": "$eingespeist30Tage/1000 * $einspeiseVerguetung * (-1)",
     "type": "math"
    },
    {
     "expression": "$zugekauftKosten30Tage + $einspeiseVerguetung30Tage",
     "type": "math"
    }
   ]
  },
  {
   "title": "PV Anlage Amortisation",
   "type": "stat",
   "description": "Bei weniger als 365 Tagen wird anhand der bisherigen Daten auf das Jahr hochgerechnet mit entsprechender Ungenauigkeit je nach erfasstem Zeitraum.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$verbrauchGesamt/1000 * $stromPreis",
     "type": "math"
    },
    {
     "expression": "$zugekauftGesamt/1000 * $stromPreis",
     "type": "math"
    },
    {
     "expression": "$eingespeistGesamt/1000 * $einspeiseVerguetung",
     "type": "math"
    },
    {
     "expression": "$zugekauftKosten - $einspeiseVerguetungGesamt",
     "type": "math"
    },
    {
     "expression": "$volleStromkosten-$zugekauftKosten+$einspeiseVerguetungGesamt",
     "type": "math"
    },
    { "expression": "taeglichesNetz", "reducer": "count", "type": "reduce" },
    {
     "expression": "$kapitalrueckfluss*365/$anzahlGemesseneTage",
     "type": "math"
    },
    {
     "expression": "$pvAnschaffungspreis/($kapitalrueckflussPrognoseJahr - $jaehrlicheKosten)",
     "type": "math"
    },
    {
     "expression": "($kapitalrueckflussPrognoseJahr - $jaehrlicheKosten)/$pvAnschaffungspreis",
     "type": "math"
    }
   ]
  },
  {
   "title": "Speicher Amortisation",
   "type": "stat",
   "description": "Bei weniger als 365 Tagen wird anhand der bisherigen Daten auf das Jahr hochgerechnet mit entsprechender Ungenauigkeit je nach erfasstem Zeitraum.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "taeglicheMessung", "reducer": "count", "type": "reduce" },
    {
     "expression": "$ladungBisher*365/$anzahlGemesseneTage",
     "type": "math"
    },
    {
     "expression": "$entladungBisher*365/$anzahlGemesseneTage",
     "type": "math"
    },
    {
     "expression": "1-($speicherentladenPrognose/$speicherladenPrognose)",
     "type": "math"
    },
    {
     "expression": "$speicherentladenPrognose/$speicherkapazitaet",
     "type": "math"
    },
    {
     "expression": "$speicherentladenPrognose/1000 * ($stromPreis - $einspeiseVerguetung) - ($speicherladenPrognose-$speicherentladenPrognose)/1000*$einspeiseVerguetung",
     "type": "math"
    },
    {
     "expression": "$speicherPreis/$speicherAmortisation",
     "type": "math"
    },
    {
     "expression": "$speicherAmortisation/$speicherPreis",
     "type": "math"
    }
   ]
  }
 ]
}