{
 "title": "PV Finanz",
 "tags": [ "PV" ],
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "pvAnschaffungspreis", "label": "Anschaffungspreis", "query": "24884" },
   { "name": "speicherPreis", "label": "Anschaffungspreis Speicher", "query": "5500" },
   { "name": "stromPreis", "label": "Strompreis", "query": "0.28, 0.227, 0.32" },
   { "name": "einspeiseVerguetung", "label": "Einspeisevergütung", "query": "0.082" },
   { "name": "jaehrlicheKosten", "label": "Jährliche Kosten", "query": "100" },
   { "name": "speicherkapazitaet", "label": "Speicherkapazität/Wh", "query": "9500" },
   { "name": "eVerbrauch", "label": "Elektro Verbrauch kWh/100km", "query": "18" },
   { "name": "vVerbrauch", "label": "Verbrenner Verbrauch l/100km", "query": "6" },
   { "name": "spritKosten", "label": "Spritpreis/Liter", "query": "1.70" }
  ]
 },
 "panels": [
  {
   "title": "Monatliche Kosten",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expression": "$verbrauchGesamt/1000 * $stromPreis",
     "type": "math"
    },
    {
     "expression": "$zugekauft30Tage/1000 * $stromPreis",
     "type": "math"
    },
    {
     "expression": "$eingespeist30Tage/1000 * $einspeiseVerguetung * (-1)",
     "type": "math"
    },
    {
     "expression": "$zugekauftKosten30Tage + $einspeiseVerguetung30Tage",
     "type": "math"
    }
   ]
  },
  {
   "title": "PV Anlage Amortisation",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$verbrauchGesamt/1000 * $stromPreis",
     "type": "math"
    },
    {
     "expression": "$zugekauftGesamt/1000 * $stromPreis",
     "type": "math"
    },
    {
     "expression": "$eingespeistGesamt/1000 * $einspeiseVerguetung",
     "type": "math"
    },
    {
     "expression": "$zugekauftKosten - $einspeiseVerguetungGesamt",
     "type": "math"
    },
    {
     "expression": "$volleStromkosten-$zugekauftKosten+$einspeiseVerguetungGesamt",
     "type": "math"
    },
    { "expression": "taeglichesNetz", "reducer": "count", "type": "reduce" },
    {
     "expression": "$kapitalrueckfluss*365/$anzahlGemesseneTage",
     "type": "math"
    },
    {
     "expression": "$pvAnschaffungspreis/($kapitalrueckflussPrognoseJahr - $jaehrlicheKosten)",
     "type": "math"
    },
    {
     "expression": "($kapitalrueckflussPrognoseJahr - $jaehrlicheKosten)/$pvAnschaffungspreis",
     "type": "math"
    }
   ]
  },
  {
   "title": "Speicher Amortisation",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "taeglicheMessung", "reducer": "count", "type": "reduce" },
    {
     "expression": "$ladungBisher*365/$anzahlGemesseneTage",
     "type": "math"
    },
    {
     "expression": "$entladungBisher*365/$anzahlGemesseneTage",
     "type": "math"
    },
    {
     "expression": "1-($speicherentladenPrognose/$speicherladenPrognose)",
     "type": "math"
    },
    {
     "expression": "$speicherentladenPrognose/$speicherkapazitaet",
     "type": "math"
    },
    {
     "expression": "$speicherentladenPrognose/1000 * ($stromPreis - $einspeiseVerguetung) - ($speicherladenPrognose-$speicherentladenPrognose)/1000*$einspeiseVerguetung",
     "type": "math"
    },
    {
     "expression": "$speicherPreis/$speicherAmortisation",
     "type": "math"
    },
    {
     "expression": "$speicherAmortisation/$speicherPreis",
     "type": "math"
    }
   ]
  }
 ]
}