{
 "title": "PV Monat",
 "tags": [ "PV" ],
 "time": { "from": "now/M", "to": "now/M" },
 "panels": [
  { "gridPos": { "h": 11, "w": 4, "x": 0, "y": 0 } },
  {
   "title": "Energie",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "PV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM pvDailyEnergy WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Zugekauft",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM gridDailyEnergy WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Haus",
     "query": "SELECT value * (-1) FROM homeDailyEnergy WHERE $timeFilter "
    },
    {
     "alias": "Garage",
     "query": "SELECT value * (-1) FROM loadpoint1DailyEnergy WHERE $timeFilter "
    },
    {
     "alias": "Stellplatz",
     "query": "SELECT value * (-1) FROM loadpoint2DailyEnergy WHERE $timeFilter "
    },
    {
     "alias": "Eingespeist",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value * (-1) FROM feedInDailyEnergy WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Energie/kWp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kWh/kWp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$pvEnergy/9840", "type": "math" }
   ]
  },
  {
   "title": "Maximale PV Leistung pro Tag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Maximale PV Leistung",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvPower",
     "query": "SELECT max(\"value\") FROM \"pvPower\" WHERE $timeFilter and value < 15000 GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  { "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 } },
  {
   "title": "Kennzahlen",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "1-$zugekaufteEnergie/($energieAuto+$energieHaus)",
     "type": "math"
    },
    {
     "expression": "($energiePV - $eingespeisteEnergie)/$energiePV",
     "type": "math"
    }
   ]
  },
  { "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 } },
  {
   "title": "Hausspeicher Stände",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 24 },
   "targets": [
    {
     "alias": "Speicher max",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT max(\"value\") FROM \"batterySoc\" WHERE $timeFilter and value <= 100 GROUP BY time(1d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Speicher min",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT min(\"value\") FROM \"batterySoc\" WHERE $timeFilter and value <= 100 and value > 0 GROUP BY time(1d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}