{
 "title": "EVCC: Today - Details",
 "tags": [ "PV" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "timezone", "label": "Zeitzone", "query": "${VAR_TIMEZONE}" },
   {
    "name": "peakPowerLimit",
    "label": "Filter für maximale Leistung / W",
    "query": "${VAR_PEAKPOWERLIMIT}"
   },
   { "name": "loadpointBlacklist", "label": "Blacklist für Loadpoints", "query": "${VAR_LOADPOINTBLACKLIST}" },
   {
    "name": "loadpoint",
    "label": "Ladepunkt",
    "query": {
     "query": "show tag values from chargePower with key = \"loadpoint\" where \"loadpoint\" !~ $loadpointBlacklist"
    }
   },
   { "name": "energySampleInterval", "label": "Energie Abtast Interval", "query": "${VAR_ENERGYSAMPLEINTERVAL}" }
  ]
 },
 "panels": [
  { "title": "PV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PV Energie",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"value\") /3600000 FROM \"pvPower\" \nWHERE \"value\"::field < $peakPowerLimit\n              AND (\"id\"::tag = '')\n              AND $timeFilter \nGROUP BY time(1d) tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PV $tag_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"value\") /3600000 FROM \"pvPower\" \nWHERE \"value\"::field < $peakPowerLimit\n              AND (\"id\"::tag <> '') \n              AND $timeFilter \nGROUP BY time(1d), \"id\"::tag fill(none)  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Leistung",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") FROM \"pvPower\" \nWHERE \"value\"::field < $peakPowerLimit\n              AND (\"id\"::tag = '')\n              AND $timeFilter \nGROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PV $tag_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") FROM \"pvPower\" \nWHERE \"value\"::field < $peakPowerLimit\n              AND (\"id\"::tag <> '')\n              AND $timeFilter \nGROUP BY time(1m), \"id\"::tag fill(none)  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speicherstand",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"batterySoc\" \nWHERE (\"id\"::tag = '')\n              AND $timeFilter \nGROUP BY time(1d) tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Speicher $tag_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"batterySoc\" \nWHERE (\"id\"::tag <> '')\n              AND $timeFilter \nGROUP BY time(1d), \"id\"::tag fill(none)  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speicher Leistung",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"batteryPower\" \nWHERE (\"id\"::tag = '')\n              AND $timeFilter \nGROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Speicher $tag_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"batteryPower\" \nWHERE (\"id\"::tag <> '')\n              AND $timeFilter \nGROUP BY time(1m), \"id\"::tag fill(none)  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Tarife", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Strompreis",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Max",
     "query": "SELECT max(\"value\") FROM \"tariffGrid\" WHERE $timeFilter GROUP BY time(1d) tz('$timezone')"
    },
    {
     "alias": "Durchschnitt",
     "query": "SELECT mean(\"value\") FROM \"tariffGrid\" WHERE $timeFilter GROUP BY time(1d) tz('$timezone')"
    },
    {
     "alias": "Min",
     "query": "SELECT min(\"value\") FROM \"tariffGrid\" WHERE $timeFilter GROUP BY time(1d) tz('$timezone')"
    }
   ]
  },
  {
   "title": "Strompreis",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 18 },
   "targets": [
    {
     "alias": "Preis",
     "query": "SELECT last(\"value\") FROM \"tariffGrid\" WHERE $timeFilter GROUP BY time(1h) tz('$timezone')"
    },
    {
     "alias": "Netzbezug",
     "query": "SELECT mean(\"value\") AS \"subquery\" FROM \"gridPower\" WHERE $timeFilter and value >=0 GROUP BY time($energySampleInterval) fill(0) tz('$timezone')"
    }
   ]
  },
  {
   "title": "Kosten",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "bought", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "sold", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "$boughtTotal + $soldTotal", "type": "math" }
   ]
  },
  {
   "title": "Stündliche Kosten",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    { "expression": "$tariffGrid * $grid", "type": "math" },
    { "expression": "$feedIn * $tariffFeedIn", "type": "math" }
   ]
  },
  {
   "title": "PV Vorhersage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "PV Vorhersage",
     "query": "SELECT integral(\"value\") / 3600000 FROM \"tariffSolar\" WHERE $timeFilter GROUP BY time(1d) tz('$timezone')"
    },
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"subquery\") / 3600000 FROM (SELECT max(\"value\") AS \"subquery\" FROM \"pvPower\" WHERE $timeFilter and value >=0 AND value < $peakPowerLimit AND (\"id\"::tag = '') GROUP BY time($energySampleInterval) fill(0) tz('$timezone')) WHERE $timeFilter GROUP BY time(1d) fill(0)  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Vorhersage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "PV Vorhersage",
     "query": "SELECT max(\"value\") FROM \"tariffSolar\" WHERE $timeFilter GROUP BY time(1h) tz('$timezone')"
    },
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") FROM \"pvPower\" \nWHERE \"value\"::field < $peakPowerLimit\n              AND (\"id\"::tag = '')\n              AND $timeFilter \nGROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "g/kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Max",
     "query": "SELECT max(\"value\") FROM \"tariffCo2\" WHERE $timeFilter GROUP BY time(1d) tz('$timezone')"
    },
    {
     "alias": "Durchschnitt",
     "query": "SELECT mean(\"value\") FROM \"tariffCo2\" WHERE $timeFilter GROUP BY time(1d) tz('$timezone')"
    },
    {
     "alias": "Min",
     "query": "SELECT min(\"value\") FROM \"tariffCo2\" WHERE $timeFilter GROUP BY time(1d) tz('$timezone')"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 45 },
   "targets": [
    {
     "alias": "CO2",
     "query": "SELECT last(\"value\") FROM \"tariffCo2\" WHERE $timeFilter GROUP BY time(1h) tz('$timezone')"
    },
    {
     "alias": "Netzbezug",
     "query": "SELECT mean(\"value\") AS \"subquery\" FROM \"gridPower\" WHERE $timeFilter and value >=0 GROUP BY time($energySampleInterval) fill(0) tz('$timezone')"
    }
   ]
  },
  { "title": "Netz", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Ströme/Phase",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Strom L1",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "gridCurrents",
     "query": "SELECT last(\"l1\") FROM \"gridCurrents\" WHERE $timeFilter  tz('$timezone')",
     "select": [
      [
       { "params": [ "l1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$timezone"
    },
    {
     "alias": "Strom L2",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "gridCurrents",
     "query": "SELECT last(\"l2\") FROM \"gridCurrents\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "l2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$timezone"
    },
    {
     "alias": "Strom L3",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "gridCurrents",
     "query": "SELECT mean(\"l3\") FROM \"gridCurrents\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "l3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$timezone"
    }
   ]
  },
  {
   "title": "Ströme/Phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "Strom L1",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "gridCurrents",
     "query": "SELECT mean(\"l1\") FROM \"gridCurrents\" WHERE $timeFilter GROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "l1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$timezone"
    },
    {
     "alias": "Strom L2",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "gridCurrents",
     "query": "SELECT mean(\"l2\") FROM \"gridCurrents\" WHERE $timeFilter GROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "l2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$timezone"
    },
    {
     "alias": "Strom L3",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "gridCurrents",
     "query": "SELECT mean(\"l3\") FROM \"gridCurrents\" WHERE $timeFilter GROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "l3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$timezone"
    }
   ]
  },
  {
   "title": "Leistung/Phase",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Leistung L1",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "gridPowers",
     "query": "SELECT last(\"l1\") FROM \"gridPowers\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "l1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$timezone"
    },
    {
     "alias": "Leistung L2",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "gridPowers",
     "query": "SELECT last(\"l2\") FROM \"gridPowers\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "l2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$timezone"
    },
    {
     "alias": "Leistung L3",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "gridPowers",
     "query": "SELECT last(\"l3\") FROM \"gridPowers\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "l3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$timezone"
    }
   ]
  },
  {
   "title": "Leistung/Phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Leistung L1",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "gridPowers",
     "query": "SELECT mean(\"l1\") FROM \"gridPowers\" WHERE $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "l1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Leistung L2",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "gridPowers",
     "query": "SELECT mean(\"l2\") FROM \"gridPowers\" WHERE $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "l2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Leistung L3",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "gridPowers",
     "query": "SELECT mean(\"l3\") FROM \"gridPowers\" WHERE $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "l3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Ladepunkt $loadpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 }, "repeat": "loadpoint" },
  {
   "title": "Ladeströme/Phase",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "L1 $loadpoint",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "chargeCurrents",
     "query": "SELECT last(\"l1\") FROM \"chargeCurrents\" WHERE (\"loadpoint\"::tag = '$loadpoint') AND $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "l1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "loadpoint::tag", "operator": "=", "value": "Garage" }
     ],
     "tz": "$timezone"
    },
    {
     "alias": "L2 $loadpoint",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "chargeCurrents",
     "query": "SELECT last(\"l2\") FROM \"chargeCurrents\" WHERE (\"loadpoint\"::tag = '$loadpoint') AND $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "l2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "loadpoint::tag", "operator": "=", "value": "Garage" }
     ],
     "tz": "$timezone"
    },
    {
     "alias": "L3 $loadpoint",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "chargeCurrents",
     "query": "SELECT last(\"l3\") FROM \"chargeCurrents\" WHERE (\"loadpoint\"::tag = '$loadpoint') AND $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "l3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "loadpoint::tag", "operator": "=", "value": "Garage" }
     ],
     "tz": "$timezone"
    },
    {
     "alias": "Strom $loadpoint",
     "query": "SELECT last(\"value\") FROM \"chargeCurrent\" WHERE (\"loadpoint\"::tag = '$loadpoint') AND $timeFilter tz('$timezone')"
    }
   ]
  },
  {
   "title": "Ladeströme/Phase",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "L1 $loadpoint",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "chargeCurrents",
     "query": "SELECT mean(\"l1\") FROM \"chargeCurrents\" WHERE (\"loadpoint\"::tag = '$loadpoint') AND $timeFilter GROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "l1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "loadpoint::tag", "operator": "=", "value": "Garage" }
     ],
     "tz": "$timezone"
    },
    {
     "alias": "L2 $loadpoint",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "chargeCurrents",
     "query": "SELECT mean(\"l2\") FROM \"chargeCurrents\" WHERE (\"loadpoint\"::tag = '$loadpoint') AND $timeFilter GROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "l2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "loadpoint::tag", "operator": "=", "value": "Garage" }
     ],
     "tz": "$timezone"
    },
    {
     "alias": "L3 $loadpoint",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "chargeCurrents",
     "query": "SELECT mean(\"l3\") FROM \"chargeCurrents\" WHERE (\"loadpoint\"::tag = '$loadpoint') AND $timeFilter GROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "l3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "loadpoint::tag", "operator": "=", "value": "Garage" }
     ],
     "tz": "$timezone"
    },
    {
     "alias": "Strom $loadpoint",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "chargeCurrents",
     "query": "SELECT mean(\"value\") FROM \"chargeCurrent\" WHERE (\"loadpoint\"::tag = '$loadpoint') AND $timeFilter GROUP BY time(1m) tz('$timezone')",
     "select": [
      [
       { "params": [ "l3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "loadpoint::tag", "operator": "=", "value": "Garage" }
     ],
     "tz": "$timezone"
    }
   ]
  },
  {
   "title": "Phasen",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 83 },
   "targets": [
    {
     "alias": "1 phasig: $loadpoint",
     "query": "SELECT max(\"value\") FROM \"phasesActive\" WHERE $timeFilter AND (\"loadpoint\"::tag = '$loadpoint') AND value = 1 GROUP BY time(1m), \"loadpoint\"::tag fill(none) tz('$timezone')"
    },
    {
     "alias": "3 phasig: $loadpoint",
     "query": "SELECT max(\"value\") FROM \"phasesActive\" WHERE $timeFilter AND (\"loadpoint\"::tag = '$loadpoint') AND value = 3 GROUP BY time(1m), \"loadpoint\"::tag fill(none) tz('$timezone')"
    }
   ]
  },
  {
   "title": "Ladeleistung",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "Ladeleistung $loadpoint",
     "query": "SELECT max(\"value\") FROM \"chargePower\" WHERE $timeFilter AND (\"loadpoint\"::tag = '$loadpoint') GROUP BY time(1m), \"loadpoint\"::tag fill(none) tz('$timezone')"
    }
   ]
  }
 ]
}