# Configuration options for the evcc-vm-aggregate.sh script. Must be located in the same directory as the script.


### VICTORIA METRICS DATABASE CONFIGURATION ###

# User name of the VictoriaMetrics DB. Empty, if no user is required. Default: ""
VM_USER="" 

# Password of the VictoriaMetrics DB user. Default: ""
VM_PASSWORD="" 

# If the script is run remotely, enter the host name of the remote host. Default: "localhost"
VM_HOST="localhost" 

# The port to connect to VictoriaMetrics. Default: 8428
VM_PORT=8428 


### PV CONFIGURATION ###

# Limit in W to filter out unrealistic peaks. Default: 40000
PEAK_POWER_LIMIT=40000 

# Set to false in case your home does not use a battery.
HOME_BATTERY="true"

# Set to true to collect tariff history.
DYNAMIC_TARIFF="true" 


### GENERAL CONFIGURATION ###

# Time zone as in TZ identifier column here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# IMPORTANT: The time zone must be the same as the one used on the system (default value) and the one used for displaying the Grafana dashboard.
TIMEZONE="`cat /etc/timezone`" 

# Interval in which the energy calculation is sampled. Should be at least twice the query interval of EVCC. Default: "60s" as EVCC has a default interval of 30s.
ENERGY_SAMPLE_INTERVAL="60s"

# Interval of grid tariff price updates. Default: "15m". 
# If for example your grid tariff changes in intervals of 60 minutes, change this to "1h".
# If you have static grid prices that do not change over the day, set this to "1d".
TARIFF_PRICE_INTERVAL="15m"

# Set to true to generate debug output. 
DEBUG="false" 