{
 "title": "EVCC: All-time",
 "tags": [ "PV" ],
 "time": { "from": "2023-02-28T23:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   { "name": "purchasePricePv", "label": "PV Gesamtinvestitionskosten", "query": "24884" },
   { "name": "batteryPurchasePrice", "label": "Investitionskosten Speicher", "query": "5500" },
   { "name": "runningCosts", "label": "Laufende Kosten", "query": "100" },
   { "name": "vVerbrauch", "label": "Verbrenner Verbrauch l/100km", "query": "6" },
   { "name": "spritKosten", "label": "Spritpreis/Liter", "query": "1.75" },
   { "name": "timezone", "query": "Europe/Berlin" },
   { "name": "speicherkapazitaet", "label": "Hausspeicherkapazität / Wh", "query": "${VAR_SPEICHERKAPAZITAET}" },
   {
    "name": "vehicle",
    "label": "Fahrzeug",
    "query": {
     "query": "show tag values from vehicleMonthlyEnergy with key = \"vehicle\" where \"vehicle\" !~ $vehicleBlacklist"
    }
   },
   { "name": "loadpointBlacklist", "label": "Blacklist für Loadpoints", "query": "${VAR_LOADPOINTBLACKLIST}" },
   { "name": "vehicleBlacklist", "label": "Blacklist für Fahrzeuge", "query": "${VAR_VEHICLEBLACKLIST}" }
  ]
 },
 "panels": [
  {
   "title": "Energie",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": "Energie", "gridPos": { "h": 11, "w": 3, "x": 0, "y": 1 } },
    {
     "title": "Jährlicher Ertrag",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 5, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "alias": "[[tag_year]]",
       "groupBy": [
        { "params": [ "year::tag" ], "type": "tag" }
       ],
       "measurement": "pvMonthlyEnergy",
       "query": "SELECT value, year FROM \"pvMonthlyEnergy\" WHERE $timeFilter GROUP BY \"year\"::tag",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Monatlicher Ertrag/Jahr",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 16, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT year, month, value FROM \"pvMonthlyEnergy\" tz('$timezone')",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    { "title": "Kennzahlen", "gridPos": { "h": 12, "w": 3, "x": 0, "y": 12 } },
    {
     "title": "Jährlicher Hausverbrauch",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 5, "x": 3, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "alias": "[[tag_year]]",
       "groupBy": [
        { "params": [ "year::tag" ], "type": "tag" }
       ],
       "measurement": "pvMonthlyEnergy",
       "query": "SELECT value, year FROM \"homeMonthlyEnergy\" WHERE $timeFilter GROUP BY \"year\"::tag",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Monatlicher Hausverbrauch/Jahr",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 16, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT year, month, value FROM \"homeMonthlyEnergy\"  tz('$timezone')",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Jährlicher Netzbezug",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 5, "x": 3, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "alias": "[[tag_year]]",
       "groupBy": [
        { "params": [ "year::tag" ], "type": "tag" }
       ],
       "measurement": "pvMonthlyEnergy",
       "query": "SELECT value, year FROM \"gridMonthlyEnergy\" WHERE $timeFilter GROUP BY \"year\"::tag",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Monatlicher Netzbezug/Jahr",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 16, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT year, month, value FROM \"gridMonthlyEnergy\"  tz('$timezone')",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    { "title": "Speicher", "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 } },
    {
     "title": "Jährliche Einspeisung",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 5, "x": 3, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "alias": "[[tag_year]]",
       "groupBy": [
        { "params": [ "year::tag" ], "type": "tag" }
       ],
       "measurement": "pvMonthlyEnergy",
       "query": "SELECT value, year FROM \"feedInMonthlyEnergy\" WHERE $timeFilter GROUP BY \"year\"::tag",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Monatliche Einspeisung/Jahr",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 16, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT year, month, value FROM \"feedInMonthlyEnergy\"  tz('$timezone')",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Ertragsreichste Tage",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "alias": "PV Energie",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pvPower",
       "query": "SELECT value FROM \"pvDailyEnergy\" WHERE $timeFilter tz('$timezone')",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "integral"
         },
         { "params": [ " / 3600" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "value::field", "operator": "<", "value": "10000" }
       ]
      }
     ]
    },
    {
     "title": "Höchste Einspeisungen",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "alias": "Einspeisung",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gridPower",
       "query": "SELECT value FROM \"feedInDailyEnergy\" WHERE $timeFilter tz('$timezone')",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "integral"
         },
         { "params": [ " / -3600" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "value::field", "operator": "<", "value": "0" }
       ]
      }
     ]
    },
    {
     "title": "Höchste Hausverbräuche",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "alias": "Hausverbrauch",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "homePower",
       "query": "SELECT value FROM \"homeDailyEnergy\" WHERE $timeFilter tz('$timezone')",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "integral"
         },
         { "params": [ " / 3600" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "value::field", "operator": "<", "value": "10000" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Finanzen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Monatliche Kosten",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "SELECT value FROM energyPurchasedMonthlyPrice WHERE $timeFilter  tz('$timezone')"
    },
    {
     "query": "SELECT value FROM energySoldMonthlyPrice WHERE $timeFilter  tz('$timezone')"
    },
    {
     "expression": "(abs($purchased + $sold) + ($purchased + $sold)) /2",
     "type": "math"
    },
    {
     "expression": "-(abs($purchased + $sold)- ($purchased + $sold)) /2",
     "type": "math"
    }
   ]
  },
  {
   "title": "PV Anlage Amortisation",
   "type": "stat",
   "description": "Bei weniger als 365 Tagen wird anhand der bisherigen Daten auf das Jahr hochgerechnet mit entsprechender Ungenauigkeit je nach erfasstem Zeitraum.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$potentialHomePrice + $potentialLoadpointPrice",
     "type": "math"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyPurchasedDailyPrice",
     "query": "SELECT sum(\"value\") FROM \"energyPurchasedDailyPrice\" WHERE $timeFilter TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyPurchasedDailyPrice",
     "query": "SELECT sum(\"value\") * (-1) FROM \"energySoldDailyPrice\" WHERE $timeFilter TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expression": "$energyPurchasedPrice - $energySoldPrice",
     "type": "math"
    },
    {
     "expression": "$potentialTotalPrice - $energyTotalPrice",
     "type": "math"
    },
    { "expression": "dailyMeasurement", "reducer": "count", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "expression": "$refluxOfCapital*365/$numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "$purchasePricePv / ($refluxOfCapitalYearly - $runningCosts)",
     "type": "math"
    },
    {
     "expression": "($refluxOfCapitalYearly - $runningCosts) / $purchasePricePv",
     "type": "math"
    }
   ]
  },
  {
   "title": "Speicher Amortisation",
   "type": "stat",
   "description": "Bei weniger als 365 Tagen wird anhand der bisherigen Daten auf das Jahr hochgerechnet mit entsprechender Ungenauigkeit je nach erfasstem Zeitraum.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") from chargeDailyEnergy WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") from dischargeDailyEnergy WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expression": "1-($dischargedEnergy/$chargedEnergy)",
     "type": "math"
    },
    {
     "expression": "($chargedEnergy/$speicherkapazitaet) * 365/$numberOfMeasuredDays",
     "type": "math"
    },
    { "expression": "dailyMeasurement", "reducer": "count", "settings": { "mode": "dropNN" }, "type": "reduce" },
    {
     "expression": "($batteryDischargeCost - $batteryChargeFeedInCost) * 365/$numberOfMeasuredDays",
     "type": "math"
    },
    {
     "expression": "$batteryPurchasePrice/$batteryPayback",
     "type": "math"
    },
    {
     "expression": "$batteryPayback/$batteryPurchasePrice",
     "type": "math"
    }
   ]
  },
  {
   "title": "Fahrtkosten $vehicle",
   "type": "stat",
   "description": "Werte sind grobe Schätzungen anhand Durchschnittswerte.\n\nAnnahme ist, dass das Fahrzeug hauptsächlich zuhause geladen wird. Externe Ladungen werden nicht berücksichtigt.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "repeat": "vehicle",
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "drivenKm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT spread(\"value\") FROM \"vehicleOdometerDailyMax\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expression": "$chargedEnergy/($drivenKm/100)", "type": "math" },
    {
     "alias": "Solaranteil",
     "measurement": "sessionSolarPercentage",
     "query": "SELECT mean(\"value\") FROM \"sessionSolarPercentage\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Effektiver, durchschnittlicher Preis",
     "measurement": "sessionPricePerKWh",
     "query": "SELECT mean(\"value\") FROM \"sessionPricePerKWh\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') tz('$timezone') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"potentialVehicleChargeDailyPrice\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"vehicleChargeDailyPrice\" WHERE $timeFilter AND (\"vehicle\"::tag = '$vehicle') tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expression": "$electricDriveCostNoPV - $electricDriveCost",
     "type": "math"
    },
    {
     "expression": "$drivenKm / 100 * $vVerbrauch * $spritKosten",
     "type": "math"
    },
    {
     "expression": "$iceDriveCost - $electricDriveCost",
     "type": "math"
    }
   ]
  }
 ]
}