{
 "title": "EVCC: Jahr",
 "tags": [ "PV" ],
 "time": { "from": "now-2y/y", "to": "now-2y/y" },
 "templating": {
  "list": [
   { "name": "timezone", "label": "Zeitzone", "query": "${VAR_TIMEZONE}" },
   { "name": "loadpointBlacklist", "label": "Blacklist für Loadpoints", "query": "${VAR_LOADPOINTBLACKLIST}" },
   { "name": "vehicleBlacklist", "label": "Blacklist für Fahrzeuge", "query": "${VAR_VEHICLEBLACKLIST}" }
  ]
 },
 "panels": [
  { "title": "PV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "gridPos": { "h": 12, "w": 4, "x": 0, "y": 1 } },
  {
   "title": "Energie",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "PV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value as \"pv\" FROM \"pvMonthlyEnergy\" WHERE $timeFilter TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Zugekauft",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value as \"grid\" FROM \"gridMonthlyEnergy\" WHERE $timeFilter  TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Haus",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value * (-1)  as home FROM \"homeMonthlyEnergy\" WHERE $timeFilter   TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_loadpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value * (-1)  FROM \"loadpointMonthlyEnergy\" WHERE $timeFilter AND \"loadpoint\"::tag !~ $loadpointBlacklist GROUP BY (\"loadpoint\"::tag)  TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Eingespeist",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value * (-1) as feedin FROM \"feedInMonthlyEnergy\" WHERE $timeFilter  TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 } },
  {
   "title": "Kennzahlen",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "1-$zugekaufteEnergie/($energieLadepunkte+$energieHaus)",
     "type": "math"
    },
    {
     "expression": "($energiePV - $eingespeisteEnergie)/$energiePV",
     "type": "math"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 } },
  { "gridPos": { "h": 8, "w": 20, "x": 4, "y": 19 } },
  {
   "title": "Tägliche Energie Ø",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Erzeugt/Tag",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT value FROM \"pvDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "expression": "$hausEnergie+$loadpointsEnergie",
     "type": "math"
    },
    {
     "alias": "Zugekauft/Tag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM \"gridDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energie/Tag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Erzeugt",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT \"value\" FROM \"pvDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "expression": "$hausEnergie+$loadpointsEnergie",
     "type": "math"
    },
    {
     "alias": "Zugekauft",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"gridDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Speicher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  { "gridPos": { "h": 9, "w": 4, "x": 0, "y": 37 } },
  {
   "title": "Speicher: Maximalwerte",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 37 },
   "targets": [
    {
     "alias": "Maximaler Batterie SOC/Tag",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT \"value\" FROM \"batteryMaxSoc\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speicher: Minimalwerte",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 37 },
   "targets": [
    {
     "alias": "Minimaler Batterie SOC/Tag",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT \"value\" FROM \"batteryMinSoc\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speicherladung",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Speicher laden",
     "query": "SELECT \"value\" from chargeMonthlyEnergy WHERE $timeFilter tz('$timezone')"
    },
    {
     "alias": "Speicher entladen",
     "query": "SELECT \"value\" from dischargeMonthlyEnergy WHERE $timeFilter tz('$timezone')"
    }
   ]
  },
  {
   "title": "Speichereffizienz",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expression": "$entladen/$laden", "type": "math" }
   ]
  },
  { "title": "Fahrzeuge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Fahrzeuge",
   "type": "stat",
   "description": "Verbrauch braucht erst einige Monate bis er aussagekräftig ist.  Fremdladungen werden ignoriert und verfälschen das Ergebnis.",
   "gridPos": { "h": 16, "w": 4, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Kilometerstand: $tag_vehicle",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vehicle1Odometer",
     "query": "SELECT \"value\" FROM \"vehicleOdometerDailyMax\" WHERE $timeFilter AND value > 0 AND \"vehicle\"::tag !~ $vehicleBlacklist GROUP BY \"vehicle\"::tag tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    },
    {
     "alias": "Gefahren: $tag_vehicle",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vehicle1Odometer",
     "query": "SELECT spread(\"value\") FROM \"vehicleOdometerDailyMax\" WHERE $timeFilter AND value > 0 AND \"vehicle\"::tag !~ $vehicleBlacklist GROUP BY \"vehicle\"::tag tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    },
    {
     "alias": "Energie: $tag_vehicle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")/1000 FROM \"vehicleMonthlyEnergy\" WHERE $timeFilter  AND value > 0 AND \"vehicle\"::tag !~ $vehicleBlacklist GROUP BY \"vehicle\" tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expression": "$vehicleChargedEnergy/($vehicleDrivenKm/100)",
     "type": "math"
    }
   ]
  },
  {
   "title": "Monatlich gefahrene Kilometer",
   "type": "barchart",
   "description": "Die Kilometer werden nur bei eingestecktem Fahrzeug erfasst. Wird ein Fahrzeug selten eingesteckt, können hier Kilometer fehlen.",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "targets": [
    {
     "alias": "Gefahren: $tag_vehicle",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vehicle1Odometer",
     "query": "SELECT \"value\" FROM \"vehicleMonthlyDrivenKm\" WHERE $timeFilter AND value > 0 AND \"vehicle\"::tag !~ $vehicleBlacklist GROUP BY \"vehicle\"::tag  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Monatlich geladene Energie",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Energie: $tag_vehicle",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vehicle1Odometer",
     "query": "SELECT \"value\" FROM \"vehicleMonthlyEnergy\" WHERE $timeFilter AND value>0 AND \"vehicle\"::tag !~ $vehicleBlacklist GROUP BY \"vehicle\"::tag  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Verbrauch (kWh/100km)",
   "type": "barchart",
   "description": "Die Werte sind ungenau. Externe Ladungen werden nicht berücksichtigt und die erfassten Kilometer hängen davon ab, wie oft ein Fahrzeug angesteckt wird.",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 73 },
   "targets": [
    {
     "expression": "($vehiclesEnergy/1000)/($vehiclesKm/100)",
     "type": "math"
    }
   ]
  }
 ]
}