{
 "title": "EVCC: Jahr",
 "tags": [ "PV" ],
 "time": { "from": "now/y", "to": "now/y" },
 "templating": {
  "list": [
   { "name": "timezone", "label": "Zeitzone", "query": "${VAR_TIMEZONE}" },
   { "name": "loadpointBlocklist", "label": "Blocklist für Loadpoints", "query": "${VAR_LOADPOINTBLOCKLIST}" },
   { "name": "vehicleBlocklist", "label": "Blocklist für Fahrzeuge", "query": "${VAR_VEHICLEBLOCKLIST}" }
  ]
 },
 "panels": [
  { "title": "PV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "gridPos": { "h": 12, "w": 5, "x": 0, "y": 1 } },
  {
   "title": "Energie",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "PV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value as \"pv\" FROM \"pvMonthlyEnergy\" WHERE $timeFilter TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Netzbezug",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value as \"grid\" FROM \"gridMonthlyEnergy\" WHERE $timeFilter  TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Haus",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value * (-1)  as home FROM \"homeMonthlyEnergy\" WHERE $timeFilter   TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_loadpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value * (-1)  FROM \"loadpointMonthlyEnergy\" WHERE $timeFilter AND \"loadpoint\"::tag !~ $loadpointBlocklist GROUP BY (\"loadpoint\"::tag)  TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Einspeisung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value * (-1) as feedin FROM \"feedInMonthlyEnergy\" WHERE $timeFilter  TZ('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kennzahlen",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "1 - $Netzbezug/($energieHaus + $energieLadepunkte)",
     "type": "math"
    },
    {
     "expression": "($energyPV - $Einspeisung) / $energyPV",
     "type": "math"
    }
   ]
  },
  {
   "title": "Kennzahlen",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "1-$zugekaufteEnergie/($energieLadepunkte+$energieHaus)",
     "type": "math"
    },
    {
     "expression": "($energiePV - $eingespeisteEnergie)/$energiePV",
     "type": "math"
    }
   ]
  },
  {
   "title": "Tägliche Energie Ø",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "PV/Tag",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT value FROM \"pvDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "expression": "$hausEnergie+$loadpointsEnergie",
     "type": "math"
    },
    {
     "alias": "Netzbezug/Tag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT value FROM \"gridDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energie/Tag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "PV",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT \"value\" FROM \"pvDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "expression": "$hausEnergie+$loadpointsEnergie",
     "type": "math"
    },
    {
     "alias": "Netzbezug",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"gridDailyEnergy\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Haus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Haus: Energieverteilung",
   "type": "piechart",
   "description": "Die Formel für 'Sonstige' muss je nach Verfügbarkeit von AUX und EXT Metern angepasst werden. Siehe https://github.com/ha-puzzles/evcc-grafana-dashboards/tree/main/dashboards#formel-für-sonstige-anpassen für mehr Informationen.",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expression": "$homeTotal - $consumersEnergiesSum",
     "type": "math"
    },
    {
     "alias": "$tag_title",
     "query": "SELECT value FROM consumersMonthlyEnergy WHERE $timeFilter AND \"title\"::tag !~ $loadpointBlocklist GROUP BY (\"title\"::tag) tz('$timezone')"
    },
    {
     "alias": "$tag_title",
     "query": "SELECT value FROM extMonthlyEnergy WHERE $timeFilter AND \"title\"::tag !~ $loadpointBlocklist GROUP BY (\"title\"::tag) tz('$timezone')"
    },
    {
     "alias": "$tag_title",
     "query": "SELECT value FROM auxMonthlyEnergy WHERE $timeFilter AND \"title\"::tag !~ $loadpointBlocklist GROUP BY (\"title\"::tag) tz('$timezone')"
    }
   ]
  },
  {
   "title": "Haus: Energieverbrauch",
   "type": "barchart",
   "description": "Die Formel für 'Sonstige' muss je nach Verfügbarkeit von AUX und EXT Metern angepasst werden. Siehe https://github.com/ha-puzzles/evcc-grafana-dashboards/tree/main/dashboards#formel-für-sonstige-anpassen für mehr Informationen.",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expression": "$homeTotal - $consumersEnergiesSum",
     "type": "math"
    },
    {
     "alias": "$tag_title",
     "query": "SELECT value FROM consumersMonthlyEnergy WHERE $timeFilter AND \"title\"::tag !~ $loadpointBlocklist GROUP BY (\"title\"::tag) tz('$timezone')"
    },
    {
     "alias": "$tag_title",
     "query": "SELECT value FROM extMonthlyEnergy WHERE $timeFilter AND \"title\"::tag !~ $loadpointBlocklist GROUP BY (\"title\"::tag) tz('$timezone')"
    },
    {
     "alias": "$tag_title",
     "query": "SELECT value FROM auxMonthlyEnergy WHERE $timeFilter AND \"title\"::tag !~ $loadpointBlocklist GROUP BY (\"title\"::tag) tz('$timezone')"
    }
   ]
  },
  {
   "title": "Gesamt: Energieverteilung",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Haus",
     "query": "SELECT value FROM homeMonthlyEnergy WHERE $timeFilter  tz('$timezone')"
    },
    {
     "alias": "$tag_loadpoint",
     "query": "SELECT value FROM loadpointMonthlyEnergy WHERE $timeFilter AND \"loadpoint\"::tag !~ $loadpointBlocklist GROUP BY (\"loadpoint\"::tag) tz('$timezone')"
    },
    {
     "expression": "$chargeEnergy - $dischargeEnergy",
     "type": "math"
    }
   ]
  },
  {
   "title": "Haus: Energieverteilung",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expression": "$chargeEnergy-$dischargeEnergy", "type": "math" },
    {
     "alias": "Haus",
     "query": "SELECT value FROM homeMonthlyEnergy WHERE $timeFilter  tz('$timezone')"
    },
    {
     "alias": "$tag_loadpoint",
     "query": "SELECT value FROM loadpointMonthlyEnergy WHERE $timeFilter AND \"loadpoint\"::tag !~ $loadpointBlocklist GROUP BY (\"loadpoint\"::tag) tz('$timezone')"
    }
   ]
  },
  { "gridPos": { "h": 18, "w": 5, "x": 0, "y": 48 } },
  { "gridPos": { "h": 11, "w": 19, "x": 5, "y": 48 } },
  {
   "title": "Stromkosten",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "alias": "Einkauf",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvPower",
     "query": "SELECT value FROM energyPurchasedMonthlyPrice WHERE $timeFilter  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Verkauf",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvPower",
     "query": "SELECT value FROM energySoldMonthlyPrice WHERE $timeFilter  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Speicher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  { "gridPos": { "h": 18, "w": 5, "x": 0, "y": 67 } },
  {
   "title": "Speicher: Maximalwerte",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 67 },
   "targets": [
    {
     "alias": "Maximaler Batterie SOC/Tag",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT \"value\" FROM \"batteryMaxSoc\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speicherladung",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Speicher laden",
     "query": "SELECT \"value\" from chargeMonthlyEnergy WHERE $timeFilter tz('$timezone')"
    },
    {
     "alias": "Speicher entladen",
     "query": "SELECT \"value\" from dischargeMonthlyEnergy WHERE $timeFilter tz('$timezone')"
    }
   ]
  },
  {
   "title": "Speicher: Minimalwerte",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 76 },
   "targets": [
    {
     "alias": "Minimaler Batterie SOC/Tag",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "batterySoc",
     "query": "SELECT \"value\" FROM \"batteryMinSoc\" WHERE $timeFilter tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speichereffizienz",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expression": "$entladen/$laden", "type": "math" }
   ]
  },
  { "title": "Fahrzeuge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Fahrzeuge",
   "type": "stat",
   "description": "Verbrauch braucht erst einige Monate bis er aussagekräftig ist.  Fremdladungen werden ignoriert und verfälschen das Ergebnis.",
   "gridPos": { "h": 16, "w": 5, "x": 0, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Kilometerstand: $tag_vehicle",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vehicle1Odometer",
     "query": "SELECT \"value\" FROM \"vehicleOdometerDailyMax\" WHERE $timeFilter AND value > 0 AND \"vehicle\"::tag !~ $vehicleBlocklist GROUP BY \"vehicle\"::tag tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    },
    {
     "alias": "Gefahren: $tag_vehicle",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vehicle1Odometer",
     "query": "SELECT spread(\"value\") FROM \"vehicleOdometerDailyMax\" WHERE $timeFilter AND value > 0 AND \"vehicle\"::tag !~ $vehicleBlocklist GROUP BY \"vehicle\"::tag tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    },
    {
     "alias": "Energie: $tag_vehicle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")/1000 FROM \"vehicleMonthlyEnergy\" WHERE $timeFilter  AND value > 0 AND \"vehicle\"::tag !~ $vehicleBlocklist GROUP BY \"vehicle\" tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expression": "$vehicleChargedEnergy/($vehicleDrivenKm/100)",
     "type": "math"
    }
   ]
  },
  {
   "title": "Monatlich gefahrene Kilometer",
   "type": "barchart",
   "description": "Die Kilometer werden nur bei eingestecktem Fahrzeug erfasst. Wird ein Fahrzeug selten eingesteckt, können hier Kilometer fehlen.",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "targets": [
    {
     "alias": "Gefahren: $tag_vehicle",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vehicle1Odometer",
     "query": "SELECT \"value\" FROM \"vehicleMonthlyDrivenKm\" WHERE $timeFilter AND value > 0 AND \"vehicle\"::tag !~ $vehicleBlocklist GROUP BY \"vehicle\"::tag  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Monatlich geladene Energie",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Energie: $tag_vehicle",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vehicle1Odometer",
     "query": "SELECT \"value\" FROM \"vehicleMonthlyEnergy\" WHERE $timeFilter AND value>0 AND \"vehicle\"::tag !~ $vehicleBlocklist GROUP BY \"vehicle\"::tag  tz('$timezone')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Verbrauch (kWh/100km)",
   "type": "barchart",
   "description": "Die Werte sind ungenau. Externe Ladungen werden nicht berücksichtigt und die erfassten Kilometer hängen davon ab, wie oft ein Fahrzeug angesteckt wird.",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 102 },
   "targets": [
    {
     "expression": "($vehiclesEnergy/1000)/($vehiclesKm/100)",
     "type": "math"
    }
   ]
  }
 ]
}